# Generated by Django 2.2.6 on 2020-06-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmodule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='student_info',
            name='roll_no',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
